export const ADD_ITEM_TO_APP_STATE = "ADD_ITEM_TO_APP_STATE"
export const ADD_BULK_TO_APP_STATE = "ADD_BULK_TO_APP_STATE"
export const CLEAR_APP_STATE = "CLEAR_APP_STATE"
export const APP_STATE_REMOVE_ITEM = "APP_STATE_REMOVE_ITEM"
export const APP_STATE_APPEND_ITEM = "APP_STATE_APPEND_ITEM"

export const NETWORK_AVAIABLE = "NETWORK_AVAIABLE"
export const NETWORK_UNAVAIABLE = "NETWORK_UNAVAIABLE"

export const USER_LOGGING_IN = "USER_LOGGING_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const USER_LOGGED_IN = "USER_LOGGED_IN"

export const SESSION_AUTHENTICATING = "SESSION_AUTHENTICATING"
export const SESSION_AUTHENTICATED = "SESSION_AUTHENTICATED"
export const SESSION_AUTHENTICATION_FAILED = "SESSION_AUTHENTICATION_FAILED"
export const SESSION_UNAUTHENTICATED = "SESSION_UNAUTHENTICATED"

export const REGISTER_INITIATED = "REGISTER_INITIATED"
export const REGISTER_SUCCEED = "REGISTER_SUCCEED"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const ITEM_REQUEST_INITIATED = "ITEM_REQUEST_INITIATED";
export const ITEM_REQUEST_SUCCEED = "ITEM_REQUEST_SUCCEED";
export const ITEM_REQUEST_FAILED = "ITEM_REQUEST_FAILED";

export const CATEGORY_REQUEST_INITIATED = "CATEGORY_REQUEST_INITIATED";
export const CATEGORY_REQUEST_SUCCEED = "CATEGORY_REQUEST_SUCCEED";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";

export const ORDER_REQUEST_INITIATED = "ORDER_REQUEST_INITIATED";
export const ORDER_REQUEST_SUCCEED = "ORDER_REQUEST_SUCCEED";
export const ORDER_REQUEST_FAILED = "ORDER_REQUEST_FAILED";

export const USER_REQUEST_INITIATED = "USER_REQUEST_INITIATED";
export const USER_REQUEST_SUCCEED = "USER_REQUEST_SUCCEED";
export const USER_REQUEST_FAILED = "USER_REQUEST_FAILED";

export const MASTERDATA_INITIATED = "MASTERDATA_INITIATED";
export const MASTERDATA_SUCCEED = "MASTERDATA_SUCCEED";
export const MASTERDATA_FAILED = "MASTERDATA_FAILED";