export const ADD_ITEM_TO_APP_STATE = "ADD_ITEM_TO_APP_STATE"
export const ADD_BULK_TO_APP_STATE = "ADD_BULK_TO_APP_STATE"
export const CLEAR_APP_STATE = "CLEAR_APP_STATE"
export const REMOVE_ITEM_FROM_APP_STATE = "REMOVE_ITEM_FROM_APP_STATE"
export const APPEND_ITEM_TO_APP_STATE = "APPEND_ITEM_TO_APP_STATE"

export const NETWORK_AVAIABLE = "NETWORK_AVAIABLE"
export const NETWORK_UNAVAIABLE = "NETWORK_UNAVAIABLE"
