export const ADD_ITEM_TO_APP_STATE = "ADD_ITEM_TO_APP_STATE"
export const ADD_BULK_TO_APP_STATE = "ADD_BULK_TO_APP_STATE"
export const CLEAR_APP_STATE = "CLEAR_APP_STATE"
export const REMOVE_ITEM_FROM_APP_STATE = "REMOVE_ITEM_FROM_APP_STATE"
export const APPEND_ITEM_TO_APP_STATE = "APPEND_ITEM_TO_APP_STATE"

export const NETWORK_AVAIABLE = "NETWORK_AVAIABLE"
export const NETWORK_UNAVAIABLE = "NETWORK_UNAVAIABLE"

export const USER_LOGGING_IN = "USER_LOGGING_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const USER_LOGGED_IN = "USER_LOGGED_IN"

export const SESSION_AUTHENTICATING = "SESSION_AUTHENTICATING"
export const SESSION_AUTHENTICATED = "SESSION_AUTHENTICATED"
export const SESSION_AUTHENTICATION_FAILED = "SESSION_AUTHENTICATION_FAILED"
export const SESSION_UNAUTHENTICATED = "SESSION_UNAUTHENTICATED"

export const REGISTER_INITIATED = "REGISTER_INITIATED"
export const REGISTER_SUCCEED = "REGISTER_SUCCEED"
export const REGISTER_FAILED = "REGISTER_FAILED"